# config.toml
# Example replication-manager configuration file

# change the service file  in /etc/systemd/system/replication-manager.service to looks like :
# replication-manager  --config=./etc/config.toml.sample  --cluster=Cluster01,Cluster_Test_2_Nodes monitor

# TOPOLOGY
# --------

[cluster1]
title = "cluster1"
db-servers-hosts = "db1,db2"
db-servers-prefered-master = "db1"
db-servers-credential = "root:mariadb"
db-servers-connect-timeout = 1

replication-credential = "root:mariadb"
prov-db-agents = "s18-control-plane-vrplg,s18-md-0-4kzvt"
prov-db-service-type = "docker"
prov-db-docker-img = "mariadb:10.11"
prov-db-tags = "semisync,innodb,noquerycache,threadpool,logslow,smallredolog"


[Default]
prov-orchestrator = "kube"
prov-net-cni  = true
prov-net-cni-cluster = "cluster.local"
kube-config = "/Users/apple/.kube/config"
http-bootstrap-button   = true
