## config.toml
## Example replication-manager configuration file

## change the service file  in /etc/systemd/system/replication-manager.service to looks like :
## replication-manager-osc  --config=./etc/config.toml.sample  --cluster=Cluster01,Cluster_Test_2_Nodes monitor

[MasterSlaveProxysql]
title = "MasterSlaveProxysql"

prov-orchestrator = "local"
db-servers-hosts = "127.0.0.1:3313,127.0.0.1:3314"
db-servers-prefered-master = "127.0.0.1:3313"
db-servers-credential = "root:mariadb"
db-servers-connect-timeout = 1
replication-credential = "root:mariadb"

proxysql = true
proxysql-bootstrap = true
proxysql-bootstrap-hostgroups = true
proxysql-port=3303
proxysql-admin-port = 6032
proxysql-servers="127.0.0.1"
proxysql-multiplexing = false
proxysql-password = "admin"
proxysql-user = "admin"
