[Default]

include = "/etc/replication-manager/cluster.d"
prov-orchestrator = "onpremise"


# To preserve settings changed using clients between restart
# Default  load config from /etc if any config found in a cluster directory it read only cluster variables not defined in etc
# Use the merge command line option in sudo to overwrite system config of a cluster proposed by api users

# monitoring-save-config = true

# To enable ssh to database and proxy hosts, use ssh-keygen ssh-copy-id for first deployment
# onpremise-ssh = true
# onpremise-ssh-credential = "root:"
# scheduler-jobs-ssh = true

#T he network address of this replocation-manager
#monitoring-address = "127.0.0.1"

## Timeout in seconds between consecutive monitoring
monitoring-ticker = 2

#########
## LOG ##
#########

log-file = "/var/log/replication-manager.log"
log-heartbeat = false


##########
## HTTP ##
##########

http-server = true
http-bind-address = "0.0.0.0"
http-port = "10001"
http-auth = false
http-session-lifetime =   3600
http-refresh-interval = 4000

#########
## API ##
#########

api-credentials = "admin:repman"
api-credentials-acl-allow = "admin:cluster db prov"
api-port = "10005"
